route:
  group_wait: 20s        #  Частота
  group_interval: 20s   #  уведомлений 
  repeat_interval: 60s  #  в телеграм
  group_by: ['alertname', 'cluster', 'service']
  receiver: alertmanager-bot

receivers:
- name: alertmanager-bot
  webhook_configs:
  - send_resolved: true
    url: 'http://ip_telegram_bot:8080'
